# Generated by Django 3.0.3 on 2020-02-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_account', '0002_profilefeed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilefeed',
            table='Profile Feed',
        ),
    ]
